WebApplication2/Controllers/CryptController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class CryptController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
           // string line = "message: \"012222 1114142503 0313012513 03141418192102 0113 2419182119021713 06131715070119\", keyed_alphabet: \"BHISOECRTMGWYVALUZDNFJKPQX\"";
            
            return View();
        }
        [HttpPost]
        public IActionResult Index(Models.Crypt mc)
        {
            ViewData["Message"] = mc.CryptLine();
            ViewData["MessageComp"] = Cryptos.Result(mc.CryptLine());
            return View();
        }

    }

    public class Cryptos
    {
        public static string Result(string value)
        {
            var Mass = value.Split(',');
            var message2 = Convert.ToString(Mass[0]).Substring(10);
            var message = Convert.ToString(Mass[0]).Remove(0, 10).TrimEnd('\"');
            string key = Convert.ToString(Mass[1]).Remove(0, 18).TrimEnd('\"');
            Alphabet a = new Alphabet();
            List<string> str = new List<string>();
            try
            {
                for (int i = 0; i < message.Length; i++)
                {
                    char numm = message[i];
                    char numm2 = message[i + 1];
                    if (message[i] == ' ')
                    {
                        str.Add(" ");
                    }

                    else
                    {
                        string res = String.Concat((int)Char.GetNumericValue(numm), (int)Char.GetNumericValue(numm2));
                        int indx = Int32.Parse(res);
                        char c = Convert.ToChar(a.CompAlph.Substring(indx, 1));
                        int inx = key.IndexOf(c);
                        str.Add(a.CompAlph.Substring(inx, 1));
                        i++;
                    }
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
            string rres ="";
            foreach (var sti in str)
            {
                rres += sti; 
            }
            return rres;
        }
    }
    

    public class Alphabet
    {
        static string alph = "abcdefghijklmnopqrstuvwxyz";
        public string CompAlph = Convert.ToString(alph).ToUpper();
    }
}

WebApplication2/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication2</title>

    <environment names="Development">
       
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" type="text/css" href="~/lib/semantic/dist/semantic.css">

       
        <script src="assets/library/jquery.min.js"></script>
        <script src="~/lib/semantic/dist/semantic.js">
        <script src="~/lib/semantic/dist/components/visibility.js"></script>
        <script src="~/lib/semantic/dist/components/sidebar.js"></script>
        <script src="~/lib/semantic/dist/components/transition.js"></script>
        <script>
            $(document)
                .ready(function () {

                    // fix menu when passed
                    $('.masthead')
                        .visibility({
                            once: false,
                            onBottomPassed: function () {
                                $('.fixed.menu').transition('fade in');
                            },
                            onBottomPassedReverse: function () {
                                $('.fixed.menu').transition('fade out');
                            }
                        })
                        ;

                    // create sidebar and attach to menu open
                    $('.ui.sidebar')
                        .sidebar('attach events', '.toc.item')
                        ;

                })
                ;
        </script>
    </environment>
    <environment names="Staging,Production">
        
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <div class="ui modal" id="myModal">
        <i class="close icon"></i>
        <div class="header">
            Profile Picture
        </div>

        <div class="actions">
            <div class="ui black deny button">
                Nope
            </div>
            <div class="ui positive right labeled icon button">
                Yep, that's me
                <i class="checkmark icon"></i>
            </div>
        </div>
    </div>

   
    <div class="pusher">
        <div class="ui inverted vertical masthead center aligned segment">
            <div class="ui container">
                <div class="ui large secondary inverted pointing menu">
                    <a class="toc item">
                        <i class="sidebar icon"></i>
                    </a>
                  

                    @Html.ActionLink("Home", "Index", "Home",null, new { @class = "item" }  )
                    @Html.ActionLink("Contact", "Contact", "Home", null, new { @class = "item" })
                    @Html.ActionLink("About", "About", "Home", null, new { @class = "item" })
                    
                    <div class="right item">
                        <a data-toggle="modal" data-target="#myModal" class="ui inverted button">log In</a> 
                        <a class="ui inverted button">Sign Up</a>
                    </div>
                </div>
            </div>
            <div class="ui text container">
                <h1 class="ui inverted header">
                   Slogan - my company
                </h1>
                <h2>continue...</h2>
               @Html.ActionLink("DeCrypt", "Index", "Crypt", null, new { @class = "ui huge primary button" })
                @Html.ActionLink("EnCrypt", "Index", "EnCrypt", null, new { @class = "ui huge green button" })
                @Html.ActionLink("CryptoChat", "Index", "CryptoChat", null, new { @class = "ui huge orange button" })
            </div>
        </div>
        @RenderBody()
    </div>
   
   

    <script>
           $('.long.modal')
            .modal('show');
    </script>

    

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>